"""create insight table

Revision ID: 000350dbd195
Revises: d53324b9b5a2
Create Date: 2026-10-07 14:35:19.565757

CHECKLIST DE REVISÃO (ADR-002, secao 2.4):
  [x] Autogenerate foi lido linha a linha? Sim. Gerou apenas a tabela
      `insight`, a FK para `form_responses` e o índice em
      `form_response_id` — nada de outros domínios.
  [x] Renomeação virou drop+create? Não se aplica: a migration só cria a
      tabela `insight`, não renomeia nada.
  [x] Mudança destrutiva foi dividida em passos? Não se aplica: não há
      remoção nem alteração de estrutura existente.
  [x] `alembic heads` conferido antes de abrir o PR? Sim, um head só
      (000350dbd195), com `down_revision` em d53324b9b5a2, conferido com
      `alembic current` antes de gerar.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "000350dbd195"
down_revision: str | None = "d53324b9b5a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insight",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("form_response_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["form_response_id"],
            ["form_responses.id"],
            name="fk_insight_form_response_id_form_responses",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_insight_form_response_id"),
        "insight",
        ["form_response_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_insight_form_response_id"), table_name="insight")
    op.drop_table("insight")
    # ### end Alembic commands ###
