"""drop user role

Revision ID: 28e9a13197f4
Revises: 87beb54d929a
Create Date: 2026-09-30 00:55:53.576619

Passo "remover" da troca do papel (CREED-32, task 6): o papel de acesso mora em
`links.role` desde a entrega 1, e ninguém mais lê `user.role`. Aqui `user.link_id`
passa a ser obrigatório, e `user.role` e o tipo `userrole` saem.

Antes de alterar, a revisão confere se há usuário sem vínculo. Se houver, ela para
com uma mensagem que diz o que fazer, em vez de deixar o Postgres falhar no
`SET NOT NULL` com um erro genérico. Nada é alterado nesse caso.

O `downgrade()` recria `role` preenchida com o papel do vínculo (`links.role`), não
com o valor que a coluna tinha: esse se perde no `upgrade`, e desde a entrega 1
ninguém o lia. Assim a coluna volta `NOT NULL`, como em `87beb54d929a`. Rollback de
verdade se faz avançando com uma revisão nova (conventions/migrations.md, regra 5).

CHECKLIST DE REVISÃO (ADR-002, secao 2.4):
[x] Autogenerate foi lido linha a linha — acrescentada a conferência de usuários sem
    vínculo e o drop do tipo `userrole`, que o autogenerate não gera. No downgrade,
    `role` voltava `NOT NULL` e sem valor, o que falha com linhas na tabela; agora
    entra nulável, é preenchida com `links.role` e só então vira `NOT NULL`. O tipo
    é recriado antes da coluna.
[x] Renomeação virou drop+create? — não: `role` sai de vez, o papel já está em
    `links.role`. Não é rename.
[x] Mudança destrutiva foi dividida em passos — sim. Adicionar: `b9fa0c109598`
    (entrega 1 da CREED-32, outro PR), que cria `links` e `user.link_id` nulável.
    Migrar dados: o `scripts/seed_local.py` da entrega 1, rodado por cada pessoa,
    que liga o usuário de dev a um vínculo.
    Remover: esta revisão.
[x] `alembic heads` conferido antes de abrir o PR — apenas uma head.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "28e9a13197f4"
down_revision: str | None = "87beb54d929a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # O `upgrade` inteiro roda numa transação só (alembic/env.py): num banco que
    # ainda não tinha a entrega 1, esta falha a desfaz junto, e `user.link_id` nem
    # existe. Por isso o primeiro passo da mensagem é parar na revisão anterior.
    # Apagar, e não ligar a um vínculo: só banco local tem usuário, e o seed
    # recria o de dev já com vínculo. O `DELETE` da mensagem é só texto.
    #
    # A conferência roda no Postgres, e não num `SELECT` lido pelo Python: assim
    # ela também entra no script de `alembic upgrade --sql`, que não conecta a
    # banco nenhum. Dentro do `RAISE`, a mensagem não pode ter aspas simples nem `%`.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM "user" WHERE link_id IS NULL) THEN
                RAISE EXCEPTION 'Há usuário(s) sem vínculo (user.link_id nulo). Rode `alembic upgrade 87beb54d929a`, apague-os com `DELETE FROM "user" WHERE link_id IS NULL`, rode `alembic upgrade head` de novo e depois `python scripts/seed_local.py`, que recria o dev@creed.example.com já com vínculo.';
            END IF;
        END $$
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "link_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("user", "role")
    # ### end Alembic commands ###

    # O autogenerate não remove o tipo junto com a coluna.
    sa.Enum(name="userrole").drop(op.get_bind(), checkfirst=True)


def downgrade() -> None:
    # O tipo precisa existir antes da coluna: `add_column` não o cria.
    userrole = postgresql.ENUM("ADMIN", "GESTOR", "RESPONDENTE", name="userrole")
    userrole.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    # Nulável só até ser preenchida: `ADD COLUMN ... NOT NULL` falha com linhas na
    # tabela, e não há default que sirva para todo usuário.
    op.add_column(
        "user",
        sa.Column(
            "role",
            postgresql.ENUM(name="userrole", create_type=False),
            nullable=True,
        ),
    )

    # O papel volta do vínculo (ver docstring). Todo usuário tem um, porque
    # `link_id` ainda é `NOT NULL` aqui. `roles` e `userrole` têm os mesmos
    # rótulos, então a conversão passa pelo texto sem perder nada.
    op.execute(
        'UPDATE "user" SET role = links.role::text::userrole '
        'FROM links WHERE "user".link_id = links.id'
    )
    op.alter_column("user", "role", existing_type=userrole, nullable=False)

    op.alter_column("user", "link_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
