"""create answer table

Revision ID: 40c65a5d6177
Revises: 49ef1d2c7b7e
Create Date: 2026-09-27 13:09:22.645770

CHECKLIST DE REVISÃO (ADR-002, secao 2.4):
  [x] Autogenerate foi lido linha a linha? Sim. Removi à mão duas operações
      sobre `form_responses` (drop do índice e create do unique constraint)
      que o autogenerate trouxe por drift entre o model da CREED-34 e o
      banco — não são desta tabela.
  [x] Renomeação virou drop+create? Não se aplica: a migration só cria a
      tabela `answer`, não renomeia nada.
  [x] Mudança destrutiva foi dividida em passos? Não se aplica: não há
      remoção nem alteração de estrutura existente.
  [x] `alembic heads` conferido antes de abrir o PR? Sim, um head só
      (40c65a5d6177). Ciclo upgrade → downgrade → upgrade rodado duas vezes,
      mais teardown completo do volume, reproduzindo a mesma estrutura.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "40c65a5d6177"
down_revision: str | None = "49ef1d2c7b7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answer",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("option_id", sa.UUID(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_answer_question_id"), "answer", ["question_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_answer_question_id"), table_name="answer")
    op.drop_table("answer")
    # ### end Alembic commands ###
