"""form_response_table

Revision ID: 49ef1d2c7b7e
Revises: 0b0ad39d779a
Create Date: 2026-09-18 18:32:32.224342

CHECKLIST DE REVISÃO (ADR-002, secao 2.4):
[x] Autogenerate foi lido linha a linha — ajustados índices, unicidade e remoção do tipo ENUM no downgrade.
[x] Renomeação virou drop+create? — não houve renomeação de tabela já exis tente; a migration ainda não havia sido aplicada.
[x] Mudança destrutiva foi dividida em passos — não há alteração destrutiva sobre dados existentes nesta migration.
[x] `alembic heads` conferido antes de abrir o PR — apenas uma head.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "49ef1d2c7b7e"
down_revision: str | None = "0b0ad39d779a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_responses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("vinculo_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "SUBMITTED", name="formresponsestatus"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_form_responses_form_id",
        "form_responses",
        ["form_id"],
    )

    op.create_index(
        "ix_form_responses_vinculo_id",
        "form_responses",
        ["vinculo_id"],
    )

    op.create_index(
        "uq_form_responses_form_id_vinculo_id",
        "form_responses",
        ["form_id", "vinculo_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_form_responses_form_id_vinculo_id",
        table_name="form_responses",
    )
    op.drop_index(
        "ix_form_responses_vinculo_id",
        table_name="form_responses",
    )
    op.drop_index(
        "ix_form_responses_form_id",
        table_name="form_responses",
    )
    op.drop_table("form_responses")
    sa.Enum(name="formresponsestatus").drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
