"""cria tabela documents

Revision ID: 67f0ab028c26
Revises: 0b0ad39d779a
Create Date: 2026-09-14 10:29:34.868815

CHECKLIST DE REVISÃO (ADR-002, secao 2.4):
  [ ] Autogenerate foi lido linha a linha?
  [ ] Renomeação virou drop+create? (perde dados — corrigir para op.alter_column)
  [ ] Mudança destrutiva foi dividida em passos (adicionar -> migrar -> remover)?
  [ ] `alembic heads` conferido antes de abrir o PR?
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "67f0ab028c26"
down_revision: str | None = "0b0ad39d779a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "CPF",
                "CNPJ",
                "NIF",
                "NIPC",
                "PASSAPORTE",
                "VAT_EU",
                "OUTRO",
                name="doc_type",
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=100), nullable=False),
        sa.Column("issuing_country", sa.String(length=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "value", name="uq_documents_type_value"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documents")
    # `create_table` cria o tipo implicitamente; `drop_table` NÃO o remove.
    sa.Enum(name="doc_type").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
