"""create dashboards table

Revision ID: 841568432f19
Revises: d53324b9b5a2
Create Date: 2026-10-07 17:39:49.608968

CHECKLIST DE REVISÃO (ADR-002, secao 2.4):
  [X] Autogenerate foi lido linha a linha?
  [N/A] Renomeação virou drop+create? (perde dados — corrigir para op.alter_column)
  [N/A] Mudança destrutiva foi dividida em passos (adicionar -> migrar -> remover)?
  [X] `alembic heads` conferido antes de abrir o PR?
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "841568432f19"
down_revision: str | None = "d53324b9b5a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["form_id"], ["form_responses.id"], name="fk_dashboard_form_id_form_responses"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="fk_dashboard_user_id_user"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dashboards")
    # ### end Alembic commands ###
