"""create questions table

Revision ID: a54224f93adf
Revises: 49ef1d2c7b7e
Create Date: 2026-09-25 10:54:17.570172

CHECKLIST DE REVISÃO (ADR-002, secao 2.4):
[x] Autogenerate foi lido linha a linha — removidas duas linhas (drop_index/
    create_unique_constraint em form_responses) que não são desta migration: é uma
    divergência pré-existente entre o model de FormResponse e a migration que o
    criou (unicidade como índice, não como constraint). Corrigir isso é fora do
    escopo da CREED-351, então fica anotado, não corrigido aqui.
[x] Renomeação virou drop+create? — não houve renomeação; tabela nova.
[x] Mudança destrutiva foi dividida em passos — não há alteração destrutiva sobre
    dados existentes; `questions` nasce vazia.
[x] `alembic heads` conferido antes de abrir o PR — uma única head.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a54224f93adf"
down_revision: str | None = "49ef1d2c7b7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("OBJECTIVE", "DESCRIPTIVE", name="questiontype"),
            nullable=False,
        ),
        sa.Column(
            "section",
            sa.Enum("PROFILE", "ASSESSMENT", "CLOSING", name="questionsection"),
            nullable=False,
        ),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column(
            "prisma",
            sa.Enum(
                "HUMAN_PLASTICITY",
                "ENTREPRENEURSHIP",
                "MULTICULTURALISM",
                "NEUROINNOVATION",
                "DECISION_MAKING",
                name="prisma",
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "form_id", "order_index", name="uq_questions_form_id_order_index"
        ),
    )
    op.create_index(op.f("ix_questions_form_id"), "questions", ["form_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_form_id"), table_name="questions")
    op.drop_table("questions")
    # ### end Alembic commands ###
    # Apagar a tabela não apaga os tipos enum do Postgres — sem isto, um
    # downgrade seguido de upgrade falha com "type already exists" (mesmo
    # padrão de 49ef1d2c7b7e_form_response_table.py).
    sa.Enum(name="questiontype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="questionsection").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="prisma").drop(op.get_bind(), checkfirst=True)
