"""create vinculos and user.vinculo_id

Revision ID: b9fa0c109598
Revises: 49ef1d2c7b7e
Create Date: 2026-09-27 21:44:20.016118

CHECKLIST DE REVISÃO (ADR-002, secao 2.4):
[x] Autogenerate foi lido linha a linha — nomeada a unique de `user.vinculo_id`,
    acrescentado o drop dos tipos `vinctype` e `roles` no downgrade, e removida a troca
    do índice único de `form_responses` por constraint, que o autogenerate trouxe por
    drift da revisão 49ef1d2c7b7e e não é desta tarefa.
[x] Renomeação virou drop+create? — não há renomeação: só tabela nova e coluna nova.
[x] Mudança destrutiva foi dividida em passos — nada é removido. `user.vinculo_id` nasce
    nulável, então as linhas que já existem em `user` ficam com NULL; `user.role` não é
    tocado (sai na task 6, em outro PR).
[x] `alembic heads` conferido antes de abrir o PR — apenas uma head.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b9fa0c109598"
down_revision: str | None = "49ef1d2c7b7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vinculos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("participant_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("setor_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("EMPREGO", "MENTORIA", "ACADEMICO", "PESSOAL", name="vinctype"),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "GESTOR", "RESPONDENTE", name="roles"),
            nullable=False,
        ),
        sa.Column(
            "start_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vinculos_organization_id"),
        "vinculos",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vinculos_participant_id"),
        "vinculos",
        ["participant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vinculos_setor_id"),
        "vinculos",
        ["setor_id"],
        unique=False,
    )

    # Só depois da tabela: a FK de `user.vinculo_id` aponta para ela.
    op.add_column("user", sa.Column("vinculo_id", sa.UUID(), nullable=True))
    op.create_unique_constraint("uq_user_vinculo_id", "user", ["vinculo_id"])
    op.create_foreign_key(
        "fk_user_vinculo_id_vinculos",
        "user",
        "vinculos",
        ["vinculo_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_vinculo_id_vinculos", "user", type_="foreignkey")
    op.drop_constraint("uq_user_vinculo_id", "user", type_="unique")
    op.drop_column("user", "vinculo_id")

    op.drop_index(op.f("ix_vinculos_setor_id"), table_name="vinculos")
    op.drop_index(op.f("ix_vinculos_participant_id"), table_name="vinculos")
    op.drop_index(op.f("ix_vinculos_organization_id"), table_name="vinculos")
    op.drop_table("vinculos")

    # Só os tipos criados aqui. `userrole` e `recordstatus` continuam em uso pelo `user`.
    sa.Enum(name="roles").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="vinctype").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
