"""create links and user.link_id

Revision ID: b9fa0c109598
Revises: 49ef1d2c7b7e
Create Date: 2026-09-27 21:44:20.016118

Os nomes seguem o ADR-0005 (identificador em inglês): o vínculo do `.dbml` é a
tabela `links`, e o setor é `department_id`. A revisão nasceu com os nomes em
português (`vinculos`, `vinculo_id`, `setor_id`, `vinctype`) e foi reescrita no lugar
antes de sair da máquina de quem a criou: nenhum outro banco aplicou aquela versão.

CHECKLIST DE REVISÃO (ADR-002, secao 2.4):
[x] Autogenerate foi lido linha a linha — nomeada a unique de `user.link_id`,
    acrescentado o drop dos tipos `linktype` e `roles` no downgrade, e removida a troca
    do índice único de `form_responses` por constraint, que o autogenerate trouxe por
    drift da revisão 49ef1d2c7b7e e não é desta tarefa.
[x] Renomeação virou drop+create? — não há renomeação: só tabela nova e coluna nova.
[x] Mudança destrutiva foi dividida em passos — nada é removido. `user.link_id` nasce
    nulável, então as linhas que já existem em `user` ficam com NULL; `user.role` não é
    tocado (sai na task 6, em outro PR).
[x] `alembic heads` conferido antes de abrir o PR — apenas uma head.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b9fa0c109598"
down_revision: str | None = "49ef1d2c7b7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("participant_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("EMPREGO", "MENTORIA", "ACADEMICO", "PESSOAL", name="linktype"),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "GESTOR", "RESPONDENTE", name="roles"),
            nullable=False,
        ),
        sa.Column(
            "start_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_links_organization_id"),
        "links",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_links_participant_id"),
        "links",
        ["participant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_links_department_id"),
        "links",
        ["department_id"],
        unique=False,
    )

    # Só depois da tabela: a FK de `user.link_id` aponta para ela.
    op.add_column("user", sa.Column("link_id", sa.UUID(), nullable=True))
    op.create_unique_constraint("uq_user_link_id", "user", ["link_id"])
    op.create_foreign_key(
        "fk_user_link_id_links",
        "user",
        "links",
        ["link_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_link_id_links", "user", type_="foreignkey")
    op.drop_constraint("uq_user_link_id", "user", type_="unique")
    op.drop_column("user", "link_id")

    op.drop_index(op.f("ix_links_department_id"), table_name="links")
    op.drop_index(op.f("ix_links_participant_id"), table_name="links")
    op.drop_index(op.f("ix_links_organization_id"), table_name="links")
    op.drop_table("links")

    # Só os tipos criados aqui. `userrole` e `recordstatus` continuam em uso pelo `user`.
    sa.Enum(name="roles").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="linktype").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
