"""liga as tabelas da sprint 2

Revision ID: d53324b9b5a2
Revises: 28e9a13197f4
Create Date: 2026-09-30 12:12:09.535527

Integração da sprint 2 (CREED-47, task 1). As tabelas da sprint nasceram em paralelo,
sem FK entre si. Aqui entram as FKs cujo alvo já existe, e a coluna que liga cada
resposta à sua resposta de formulário:

- `links.participant_id`      -> `participants.id`
- `questions.form_id`         -> `form.id`
- `form_responses.form_id`    -> `form.id`
- `form_responses.vinculo_id` -> `links.id`
- `answer.question_id`        -> `questions.id`
- `answer.form_response_id`   -> `form_responses.id` (coluna nova, `NOT NULL`)

Ficam de fora `organization_id`, `department_id` e `answer.option_id`: as tabelas alvo
ainda não existem (CREED-38, CREED-39 e CREED-37).

Antes de alterar, a revisão confere se há linha apontando para o que não existe. Se
houver, ela para com uma mensagem que diz o que fazer, em vez de deixar o Postgres
falhar no `ADD CONSTRAINT` com um erro genérico. Ela não apaga nem insere nada: só banco
local tem esses dados, e quem decide o que fazer com eles é quem os criou.

CHECKLIST DE REVISÃO (ADR-002, secao 2.4):
[x] Autogenerate foi lido linha a linha — as seis FKs e o índice saíram como o model
    descreve, com os nomes explícitos. Acrescentadas à mão as conferências de órfãos,
    que o autogenerate não gera. As operações foram reagrupadas por tabela, sem mudar
    nenhuma.
[x] Renomeação virou drop+create? — não há renomeação. `form_responses.vinculo_id`
    continua com o nome antigo de propósito (rename é outro PR).
[x] Mudança destrutiva foi dividida em passos — não há mudança destrutiva: só entram
    constraints e uma coluna. `answer.form_response_id` nasce `NOT NULL` sem
    `server_default` porque `answer` está vazia em todo lugar (nenhuma rota nem seed
    grava nela); a conferência abaixo garante isso antes do `ADD COLUMN`.
[x] `alembic heads` conferido antes de abrir o PR — apenas uma head.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d53324b9b5a2"
down_revision: str | None = "28e9a13197f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # A conferência roda no Postgres, e não num `SELECT` lido pelo Python: assim ela
    # também entra no script de `alembic upgrade --sql`. O `upgrade` inteiro roda numa
    # transação só (alembic/env.py), então nada fica pela metade. Dentro do `RAISE`, a
    # mensagem não pode ter aspas simples nem `%`.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM links
                WHERE participant_id NOT IN (SELECT id FROM participants)
            ) THEN
                RAISE EXCEPTION 'Há vínculo(s) em links apontando para participante inexistente. Se for o vínculo do seed (participante 00000000-0000-0000-0000-000000000002), rode `python scripts/seed_local.py`, que cria o participante, e depois `alembic upgrade head` de novo. Se for vínculo de teste manual, apague-o antes.';
            END IF;

            IF EXISTS (
                SELECT 1 FROM questions WHERE form_id NOT IN (SELECT id FROM form)
            ) THEN
                RAISE EXCEPTION 'Há pergunta(s) em questions apontando para formulário inexistente. Apague-as com `DELETE FROM questions WHERE form_id NOT IN (SELECT id FROM form)` e rode `alembic upgrade head` de novo.';
            END IF;

            IF EXISTS (
                SELECT 1 FROM form_responses
                WHERE form_id NOT IN (SELECT id FROM form)
                   OR vinculo_id NOT IN (SELECT id FROM links)
            ) THEN
                RAISE EXCEPTION 'Há resposta(s) de formulário em form_responses apontando para formulário ou vínculo inexistente. Apague-as com `DELETE FROM form_responses WHERE form_id NOT IN (SELECT id FROM form) OR vinculo_id NOT IN (SELECT id FROM links)` e rode `alembic upgrade head` de novo.';
            END IF;

            IF EXISTS (SELECT 1 FROM answer) THEN
                RAISE EXCEPTION 'A tabela answer tem linha(s), e a coluna nova answer.form_response_id é obrigatória: não há como saber a que resposta de formulário cada uma pertence. Apague-as com `DELETE FROM answer` e rode `alembic upgrade head` de novo.';
            END IF;
        END $$
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_links_participant_id_participants",
        "links",
        "participants",
        ["participant_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_questions_form_id_form", "questions", "form", ["form_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_form_responses_form_id_form", "form_responses", "form", ["form_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_form_responses_vinculo_id_links",
        "form_responses",
        "links",
        ["vinculo_id"],
        ["id"],
    )

    op.add_column("answer", sa.Column("form_response_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_answer_form_response_id"),
        "answer",
        ["form_response_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_answer_form_response_id_form_responses",
        "answer",
        "form_responses",
        ["form_response_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_answer_question_id_questions", "answer", "questions", ["question_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_answer_question_id_questions", "answer", type_="foreignkey")
    op.drop_constraint(
        "fk_answer_form_response_id_form_responses", "answer", type_="foreignkey"
    )
    op.drop_index(op.f("ix_answer_form_response_id"), table_name="answer")
    # A coluna sai com o que tiver gravado. Rollback de verdade se faz avançando com
    # uma revisão nova (conventions/migrations.md, regra 5).
    op.drop_column("answer", "form_response_id")

    op.drop_constraint(
        "fk_form_responses_vinculo_id_links", "form_responses", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_form_responses_form_id_form", "form_responses", type_="foreignkey"
    )
    op.drop_constraint("fk_questions_form_id_form", "questions", type_="foreignkey")
    op.drop_constraint(
        "fk_links_participant_id_participants", "links", type_="foreignkey"
    )
    # ### end Alembic commands ###
