"""cria tabela documentos

Revision ID: fbe44f47c336
Revises: 0b0ad39d779a
Create Date: 2026-09-13 08:49:57.730554

CHECKLIST DE REVISÃO (ADR-002, secao 2.4):
  [ ] Autogenerate foi lido linha a linha?
  [ ] Renomeação virou drop+create? (perde dados — corrigir para op.alter_column)
  [ ] Mudança destrutiva foi dividida em passos (adicionar -> migrar -> remover)?
  [ ] `alembic heads` conferido antes de abrir o PR?
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fbe44f47c336"
down_revision: str | None = "0b0ad39d779a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documentos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "CPF",
                "CNPJ",
                "NIF",
                "NIPC",
                "PASSAPORTE",
                "VAT_EU",
                "OUTRO",
                name="tipo_documento",
            ),
            nullable=False,
        ),
        sa.Column("valor", sa.String(length=100), nullable=False),
        sa.Column("pais_emissor", sa.String(length=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documentos")
    # ### end Alembic commands ###
